name: CI Docker Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pylint install
        run: apt install pylint

      - name: Lint app code
        run: pylint app.py

      - name: Log into registry
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fernandostn/contador-de-visitas:${{ github.run_number }}.0
            fernandostn/contador-de-visitas:latest